version: '3.8'

volumes:
  vol-postgres:

networks:
  net-postgres:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always 
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: q1w2e3r4
    ports:
      - '5432:5432'
    networks:
      - net-postgres
    volumes: 
      - vol-postgres:/var/lib/postgresql/data
  
  pgadmin: 
    container_name: pgadmin   
    image: dpage/pgadmin4:latest    
    ports:
      - '8083:80'
    networks:
      - net-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: maiconnovaes@gmail.com
      PGADMIN_DEFAULT_PASSWORD: q1w2e3r4